#ifndef TOUWENJIAN_H
#define TOUWENJIAN_H

#endif // TOUWENJIAN_H
#include <QWidget>
#include <QLineEdit>
#include <QMouseEvent>
#include <QKeyEvent>
#include <QFile>
#include <QFileDialog>
#include <QLabel>
#include <QPushButton>
#include <QTimerEvent>
#include <QMessageBox>
#include <QDialog>
#include <QIntValidator>
#include <QTime>
#include <cmath>
#include <algorithm>
#include "mypushbotton.h"
#include <QTextCursor>
#include <QTextEdit>
#include <QMediaPlayer>
#include <QChart>
#include <QSplineSeries>
#include <QMediaPlaylist>
#include "dialog.h"
#include "ui_dialog.h"
#include <QFileDevice>
#include <QTextStream>
#include <QTextCodec>
